import { createClient } from '@libsql/client';
import path from 'path';

export type BotMessageStatus = 'pending'|'sent'|'failed'|'paused';
export type BotMessageType = 'trade_placed'|'trade_failed'|'trade_aborted'|'alert'|'info';
export interface BotMessageInput { chatId?:string|null; messageText:string; messageType:BotMessageType; tradeId?:string|null; marketId?:string|null; marketTitle?:string|null; status?:BotMessageStatus; errorReason?:string|null; timestamp?:string }
export interface BotMessageRow extends BotMessageInput { id:number; timestamp:string; status:BotMessageStatus; telegramMessageId:string|null }
const DB_PATH=path.join(process.cwd(),'data','edgefinder.db');
let initialized=false;
const db=()=>createClient({url:`file:${DB_PATH}`});
async function ensureTable(){if(initialized)return;const c=db();try{await c.execute(`CREATE TABLE IF NOT EXISTS bot_trader_messages (id INTEGER PRIMARY KEY AUTOINCREMENT,timestamp TEXT NOT NULL,chat_id TEXT,message_text TEXT NOT NULL,message_type TEXT NOT NULL,trade_id TEXT,market_id TEXT,market_title TEXT,telegram_message_id TEXT,status TEXT NOT NULL CHECK(status IN ('pending','sent','failed','paused')),error_reason TEXT)`);await c.execute('CREATE INDEX IF NOT EXISTS idx_bot_messages_filters ON bot_trader_messages(timestamp DESC,status,message_type,market_id)');initialized=true;}finally{c.close();}}
export async function createBotMessage(input:BotMessageInput){await ensureTable();const c=db();try{const r=await c.execute({sql:`INSERT INTO bot_trader_messages(timestamp,chat_id,message_text,message_type,trade_id,market_id,market_title,status,error_reason) VALUES(?,?,?,?,?,?,?,?,?)`,args:[input.timestamp??new Date().toISOString(),input.chatId??null,input.messageText,input.messageType,input.tradeId??null,input.marketId??null,input.marketTitle??null,input.status??'pending',input.errorReason??null]});return Number(r.lastInsertRowid??0);}finally{c.close();}}
export async function updateBotMessage(id:number,update:{status:BotMessageStatus;telegramMessageId?:number|string|null;errorReason?:string|null}){await ensureTable();const c=db();try{await c.execute({sql:'UPDATE bot_trader_messages SET status=?,telegram_message_id=?,error_reason=? WHERE id=?',args:[update.status,update.telegramMessageId==null?null:String(update.telegramMessageId),update.errorReason??null,id]});}finally{c.close();}}
export async function pruneBotMessages(days=30){await ensureTable();const c=db();try{const cutoff=new Date(Date.now()-days*86_400_000).toISOString();const r=await c.execute({sql:'DELETE FROM bot_trader_messages WHERE timestamp < ?',args:[cutoff]});return Number(r.rowsAffected??0);}finally{c.close();}}
export async function getBotMessages(filters:{status?:BotMessageStatus;type?:BotMessageType;marketId?:string;since?:string;cursor?:number;limit?:number}={}){await ensureTable();const where:string[]=[];const args:(string|number)[]=[];if(filters.status){where.push('status=?');args.push(filters.status)}if(filters.type){where.push('message_type=?');args.push(filters.type)}if(filters.marketId){where.push('market_id=?');args.push(filters.marketId)}if(filters.since){where.push('timestamp>=?');args.push(filters.since)}if(filters.cursor){where.push('id<?');args.push(filters.cursor)}const limit=Math.min(200,Math.max(1,filters.limit??100));args.push(limit+1);const c=db();try{const r=await c.execute({sql:`SELECT * FROM bot_trader_messages ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY id DESC LIMIT ?`,args});const raw=r.rows as unknown as Record<string,unknown>[];const more=raw.length>limit;const page=raw.slice(0,limit);const messages:BotMessageRow[]=page.map(x=>({id:Number(x.id),timestamp:String(x.timestamp),chatId:x.chat_id==null?null:String(x.chat_id),messageText:String(x.message_text),messageType:x.message_type as BotMessageType,tradeId:x.trade_id==null?null:String(x.trade_id),marketId:x.market_id==null?null:String(x.market_id),marketTitle:x.market_title==null?null:String(x.market_title),telegramMessageId:x.telegram_message_id==null?null:String(x.telegram_message_id),status:x.status as BotMessageStatus,errorReason:x.error_reason==null?null:String(x.error_reason)}));return{messages,total:messages.length,nextCursor:more?messages.at(-1)?.id??null:null};}finally{c.close();}}
