'use client';
import { useCallback,useEffect,useState } from 'react';
import { ChevronDown,ChevronRight,RefreshCw,Send } from 'lucide-react';
import { sendBotTraderTestMessageFromBrowser } from '@/app/actions/bot-trader-mutations';
type Status='sent'|'failed'|'paused'|'pending';
interface Message {id:number;timestamp:string;messageText:string;messageType:string;marketTitle:string|null;status:Status;errorReason:string|null;telegramMessageId:string|null;}
const cls:Record<Status,string>={sent:'text-[var(--status-positive)]',failed:'text-[var(--status-negative)]',paused:'text-[var(--status-warning)]',pending:'text-[var(--status-warning)]'};

export default function BotTraderMessages(){const [messages,setMessages]=useState<Message[]>([]);const [status,setStatus]=useState<'all'|Status>('all');const [type,setType]=useState('all');const [since,setSince]=useState('');const [expanded,setExpanded]=useState<Set<number>>(new Set());const [auto,setAuto]=useState(true);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [config,setConfig]=useState<{configured:boolean;dedicated:boolean;chatId:string|null}|null>(null);const [testing,setTesting]=useState(false);
const load=useCallback(async()=>{const q=new URLSearchParams();if(status!=='all')q.set('status',status);if(type!=='all')q.set('type',type);if(since)q.set('since',new Date(`${since}T00:00:00`).toISOString());try{const r=await fetch(`/api/bot-trader/messages?${q}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed to load messages');setMessages(d.messages||[]);setConfig(d.config);setError(null);}catch(e){setError(e instanceof Error?e.message:'Failed to load messages')}finally{setLoading(false)}},[since,status,type]);
useEffect(()=>{const initialId=window.setTimeout(()=>void load(),0);if(!auto)return()=>window.clearTimeout(initialId);const intervalId=window.setInterval(()=>void load(),30_000);return()=>{window.clearTimeout(initialId);window.clearInterval(intervalId)}},[auto,load]);
const test=async()=>{if(testing||!window.confirm('Send a real test message to the configured BotTrader Telegram chat?'))return;setTesting(true);try{const result=await sendBotTraderTestMessageFromBrowser();if(!result.ok)throw new Error(result.message||'The BotTrader message test could not be sent.');await load();}catch(e){setError(e instanceof Error?e.message:'The BotTrader message test could not be sent.')}finally{setTesting(false)}};
return <section className="space-y-3" aria-label="BotTrader messages"><div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-panel)] p-3"><div><strong className="text-sm">Telegram destination</strong><div className="text-xs text-[var(--text-secondary)]">{config?.configured?`BotTrader messages → Chat ID: ${config.chatId}${config.dedicated?' (dedicated)':' (main alerts fallback)'}`:'Telegram is not configured. Set TELEGRAM_BOT_TOKEN and TELEGRAM_BOT_TRADER_CHAT_ID in .env.local.'}</div></div><button onClick={()=>void test()} disabled={!config?.configured||testing} className="flex min-h-11 items-center gap-2 rounded border border-[var(--border-strong)] px-3 text-xs disabled:opacity-40"><Send className="h-4 w-4"/>Send test message</button></div>
<div className="flex flex-wrap items-end gap-2 rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-panel)] p-3"><label className="text-xs">Status<select value={status} onChange={e=>setStatus(e.target.value as typeof status)} className="ml-2 min-h-11 rounded bg-[var(--surface-workspace)] px-2"><option value="all">All</option><option value="sent">Sent</option><option value="failed">Failed</option><option value="paused">Paused</option></select></label><label className="text-xs">Type<select value={type} onChange={e=>setType(e.target.value)} className="ml-2 min-h-11 rounded bg-[var(--surface-workspace)] px-2"><option value="all">All</option><option value="trade_placed">Trade placed</option><option value="trade_failed">Trade failed</option><option value="trade_aborted">Trade aborted</option><option value="alert">Alert</option><option value="info">Info</option></select></label><label className="text-xs">Since<input type="date" value={since} onChange={e=>setSince(e.target.value)} className="ml-2 min-h-11 rounded bg-[var(--surface-workspace)] px-2"/></label><label className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Auto-refresh 30s</label><button aria-label="Refresh messages" onClick={()=>void load()} className="min-h-11 min-w-11 rounded border border-[var(--border-strong)]"><RefreshCw className={`mx-auto h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>
{error&&<div role="alert" className="rounded border border-[var(--status-negative)]/40 p-3 text-sm text-[var(--status-negative)]">{error}</div>}<div className="overflow-hidden rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-panel)]"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs"><thead><tr className="text-left text-[var(--text-secondary)]"><th className="p-2"/><th className="p-2">Timestamp</th><th className="p-2">Type</th><th className="p-2">Market</th><th className="p-2">Status</th><th className="p-2">Message preview</th></tr></thead><tbody>{messages.map(m=>{const open=expanded.has(m.id);return <><tr key={m.id} className="border-t border-[var(--border-subtle)]"><td className="p-2"><button aria-label={`${open?'Collapse':'Expand'} message ${m.id}`} onClick={()=>setExpanded(x=>{const n=new Set(x);open?n.delete(m.id):n.add(m.id);return n})}>{open?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}</button></td><td className="whitespace-nowrap p-2">{new Date(m.timestamp).toLocaleString()}</td><td className="p-2">{m.messageType.replaceAll('_',' ')}</td><td className="max-w-52 truncate p-2">{m.marketTitle||'—'}</td><td className={`p-2 font-semibold ${cls[m.status]}`}>{m.status}</td><td className="max-w-72 truncate p-2">{m.messageText.replace(/<[^>]+>/g,'')}</td></tr>{open&&<tr key={`${m.id}-detail`}><td colSpan={6} className="border-t border-[var(--border-subtle)] bg-[var(--surface-workspace)] p-4"><pre className="whitespace-pre-wrap text-xs">{m.messageText}</pre>{m.telegramMessageId&&<div className="mt-2 text-[var(--text-secondary)]">Telegram message ID: {m.telegramMessageId}</div>}{m.errorReason&&<div className="mt-2 text-[var(--status-negative)]">{m.errorReason}</div>}</td></tr>}</>})}</tbody></table></div>{!loading&&messages.length===0&&<div className="py-10 text-center text-sm text-[var(--text-secondary)]">No BotTrader messages match these filters.</div>}</div></section>}
