'use client';

import { useEffect, useMemo, useState } from 'react';

type Episode = { id: number; market_title: string | null; market_id: string; category: string; outcome: string; strategy: string; first_seen_at: string; closed_at: string; duration_sec: number; scan_count: number; peak_roi_pct: number; peak_profit: number; peak_stake: number };
type Sort = 'opened' | 'duration' | 'roi';

export default function PhantomsPanel() {
  const [days, setDays] = useState(30); const [category, setCategory] = useState('all');
  const [rows, setRows] = useState<Episode[]>([]); const [loading, setLoading] = useState(true); const [sort, setSort] = useState<Sort>('opened');
  useEffect(() => { let live = true; setLoading(true); fetch(`/api/phantoms?days=${days}${category === 'all' ? '' : `&category=${encodeURIComponent(category)}`}`).then(r => r.ok ? r.json() : Promise.reject()).then(d => { if (live) setRows(d.episodes ?? []); }).catch(() => { if (live) setRows([]); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [days, category]);
  const categories = useMemo(() => ['all', ...Array.from(new Set(rows.map(r => r.category))).sort()], [rows]);
  const sorted = [...rows].sort((a, b) => sort === 'duration' ? b.duration_sec - a.duration_sec : sort === 'roi' ? b.peak_roi_pct - a.peak_roi_pct : Date.parse(b.first_seen_at) - Date.parse(a.first_seen_at));
  return <div className="space-y-4"><div><h2 className="text-xl font-bold">Phantom arb episodes</h2><p className="text-sm text-[#8A9BA8]">Closed opportunities observed for less than one minute.</p></div><div className="flex gap-2"><select aria-label="Date range" value={days} onChange={e => setDays(Number(e.target.value))} className="bg-[#0E1621] border border-[#182533] rounded px-2 py-1 text-sm"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={365}>All time</option></select><select aria-label="Category" value={category} onChange={e => setCategory(e.target.value)} className="bg-[#0E1621] border border-[#182533] rounded px-2 py-1 text-sm">{categories.map(c => <option key={c}>{c}</option>)}</select></div>{loading ? <div className="text-[#8A9BA8]">Loading phantom episodes…</div> : sorted.length === 0 ? <div className="rounded-lg bg-[#17212B] p-6 text-center text-[#8A9BA8]">No phantom arb episodes in this range.</div> : <div className="overflow-x-auto rounded-lg border border-[#182533]"><table className="w-full text-sm"><thead className="bg-[#0E1621] text-[#8A9BA8]"><tr>{[['Market',''],['Outcome',''],['Category',''],['Duration','duration'],['Peak ROI','roi'],['Peak profit',''],['Peak stake',''],['Scans',''],['Opened','opened']].map(([label,key]) => <th key={label} onClick={() => key && setSort(key as Sort)} className={`p-2 text-left ${key ? 'cursor-pointer' : ''}`}>{label}</th>)}</tr></thead><tbody>{sorted.map(r => <tr key={r.id} className="border-t border-[#182533]"><td className="p-2 max-w-[260px] truncate" title={r.market_title ?? r.market_id}>{r.market_title ?? r.market_id}</td><td className="p-2">{r.outcome}<div className="text-xs text-[#8A9BA8]">{r.strategy}</div></td><td className="p-2">{r.category}</td><td className="p-2">{Math.round(r.duration_sec)}s</td><td className="p-2 text-[#5DBE81]">+{Number(r.peak_roi_pct).toFixed(2)}%</td><td className="p-2">${Number(r.peak_profit).toFixed(2)}</td><td className="p-2">${Number(r.peak_stake).toFixed(2)}</td><td className="p-2">{r.scan_count}</td><td className="p-2 whitespace-nowrap">{new Date(r.first_seen_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</div>;
}
